# Generated by Django 3.1.4 on 2020-12-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('dayofweek', models.CharField(max_length=10)),
                ('nameday', models.CharField(max_length=100)),
                ('saintsday', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Deň',
                'verbose_name_plural': 'Dni',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gospel.day')),
            ],
        ),
        migrations.CreateModel(
            name='Psalm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gospel.day')),
            ],
        ),
        migrations.CreateModel(
            name='Gospel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=100)),
                ('chapter_title', models.CharField(blank=True, max_length=100, null=True)),
                ('verse', models.TextField()),
                ('text', models.TextField()),
                ('gospel_from', models.CharField(max_length=100)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gospels', to='gospel.day')),
            ],
            options={
                'unique_together': {('day', 'chapter')},
            },
        ),
    ]
